#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/lawrence/.local/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/usr/local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/mnt/c/Users/lawre/OneDrive/Documents/burise/VTA-neurons-opiates-withdrawal/EnricoEtAl2016/x86_64/.libs/libnrnmech.so" "$@"
